WINDOW_TITLE = 'Obfuscator'

FILE_PATH_LIST = 'File paths list'
REFERENCES_LIST = 'References list'
ADD_FILES = 'Add files'
START = 'Start'
STRING_A = 'String A'
STRING_B = 'String B'
MINIFY_CODE = 'Minify code'

WINDOW_WIDTH = 820
WINDOW_HEIGHT = 570

HORIZONTAL_PADDING = 30
TOP_PADDING = 37
BOTTOM_PADDING = 23

TITLE_Y_CORRECTION = 3

WIDGET_BACKGROUND_COLOR = '#2b2b2b'

PRIMARY_COLOR = '#06cc68'
