WINDOW_TITLE = 'Obfuscator v0.1'

OBFUSCATION_MODE = 'OB MODE'
DEOFUSCATE_MODE = 'DEOB MODE'

FILE_PATH_LIST = 'File paths list'
REFERENCES_LIST = 'References list'
ADD_FILES = 'Add files'
START = 'Start'
STRING_A = 'String A'
STRING_B = 'String B'
MINIFY_CODE = 'Minify code'
SAVE_DECODER_FILE_CODE = 'Save decoder file'

SAVE_DECODER_FILE = 'Save decoder file'
ALLOWED_FILE_TYPES_FOR_DECODER_FILE = 'Decoder files for Obfuscator (*.dec)'

WIDGET_BACKGROUND_COLOR = '#2b2b2b'

PRIMARY_COLOR = '#06cc68'
SECONDARY_COLOR = '#ff8c00'

SECONDARY_LIGHT_COLOR = '#ffc400'
SECONDARY_EXTRA_LIGHT_COLOR = '#ffdd00'

WINDOW_WIDTH = 820
WINDOW_HEIGHT = 577

HORIZONTAL_PADDING = 30
TOP_PADDING = 37
BOTTOM_PADDING = 25

TITLE_Y_CORRECTION = 3